version: '2.3'
services:
  lolminer:
    build:
      context: .
      dockerfile: Dockerfile
    image: compscidr/lolminer:dev
    container_name: lolminer
    devices:
       - /dev/dri:/dev/dri # for GPU access
    environment:
      - COIN=AION
      - HOST=pool.us.woolypooly.com
      - PORT=33333
      - WALLET=a0ac4402b949e06ab5d97adaa31126d8964a3c8603927cbd3e028a8132e4fd98
      - MACHINE=UnRaideon8570
